services:
  inventory:
    build:
      context: .
      dockerfile: development.dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: thePassword
    restart: unless-stopped